Workaround possible mockito bug. We're doing some crazy spy stuff so I'm not surprised.
Summary:
It's not 100% clear how the bug manifests. But it's likely due to the fact that NoOpPlan was a NamedPlan, which extends Plan, which has the superClone() method we're trying to stub out.

The error message is
```
MockitoException: Checked exception is invalid for this method.
```

Reviewers: featherless, O2 Material Motion, O6 Material Motion Android platform reviewers

Reviewed By: featherless, O2 Material Motion, O6 Material Motion Android platform reviewers

Subscribers: featherless

Tags: #material_motion

Differential Revision: http://codereview.cc/D2092